In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import os
import nept

In [2]:
thisdir = os.getcwd()
data_filepath = os.path.join(thisdir, "cache", "data")
output_filepath = os.path.join(thisdir, "plots", "tmaze")
if not os.path.exists(output_filepath):
    os.makedirs(output_filepath)

In [3]:
rat = "R182"
date = "2019-04-09"

event_filepath = os.path.join(data_filepath, rat, rat+"_"+date+"_behavior", date+"_Events.nev")

In [4]:
event_labels = dict(north_feeder='TTL Output on AcqSystem1_0 board 0 port 0 value (0x0010).',
                    not_north_feeder='NOT firing feeder NorthFeeder',
                    north_pb='TTL Input on AcqSystem1_0 board 0 port 1 value (0x0010).',
                    east_feeder='TTL Output on AcqSystem1_0 board 0 port 0 value (0x0020).',
                    not_east_feeder='NOT firing feeder EastFeeder',
                    east_pb='TTL Input on AcqSystem1_0 board 0 port 1 value (0x0020).',
                    south_feeder='TTL Output on AcqSystem1_0 board 0 port 0 value (0x0040).',
                    not_south_feeder='NOT firing feeder SouthFeeder',
                    south_pb='TTL Input on AcqSystem1_0 board 0 port 1 value (0x0040).',
                    trial_start='trial start',
                    trial_end='trial end')

In [5]:
events = nept.load_events(os.path.join(data_filepath, event_filepath), event_labels)

In [19]:
feeders = ["north_feeder", "east_feeder", "south_feeder"]
for feeder in feeders:
    print(feeder)
    print(events[feeder])

north_feeder
[5095.535973 5129.952035 5166.49091  5182.53241  5204.812191 5237.055348
 5281.264504 5347.723004 5382.139066 5422.513098 5480.080285 5606.118254
 5673.768566 5699.192504 5733.999066 5758.541848 5790.354254 5824.610254
 5841.753254 5885.391691]
east_feeder
[5050.525785 5066.647348 5087.164816 5103.266316 5123.182973 5140.496223
 5158.770598 5173.35016  5192.696004 5211.15066  5226.361004 5243.243598
 5259.295066 5273.083629 5293.12041  5337.15891  5359.749098 5388.777973
 5411.207879 5432.716785 5451.902566 5473.020848 5507.116223 5542.893848
 5574.616129 5596.655629 5623.912004 5642.717066 5663.214504 5681.659129
 5705.731285 5724.12591  5744.643348 5765.250816 5798.535254 5815.217691
 5832.881316 5851.065723 5872.584629 5893.292254]
south_feeder
[5042.965535 5059.177348 5075.439066 5115.783066 5151.210473 5220.292848
 5251.644816 5265.673723 5322.379285 5399.452223 5443.841754 5462.666879
 5523.027379 5560.216879 5584.829754 5633.985441 5656.375379 5714.523129
 5808.8091

In [22]:
pbs = ["north_pb", "east_pb", "south_pb"]
for pb in pbs:
    print(pb)
    print(events[pb])

north_pb
[5095.267379 5100.658598 5100.927723 5100.955285 5100.999348 5101.107004
 5129.676316 5135.287691 5135.344098 5135.638691 5166.208754 5169.726254
 5170.650285 5170.842754 5182.24816  5187.457723 5187.743941 5187.800691
 5187.840691 5187.91416  5204.506691 5208.241629 5208.497035 5208.560254
 5208.592785 5208.629035 5236.760941 5240.781098 5240.973441 5241.098441
 5280.974066 5286.096004 5287.162254 5287.542379 5290.466285 5290.58541
 5347.427973 5356.853941 5357.148848 5357.244191 5381.871566 5386.044973
 5386.316848 5386.417941 5386.471098 5422.214191 5427.577723 5428.326879
 5428.62941  5479.80716  5493.317754 5494.560129 5495.504129 5605.84541
 5612.728754 5613.384129 5613.495379 5673.494848 5678.607629 5698.901785
 5702.722441 5703.176691 5703.330629 5733.699754 5740.436879 5741.432816
 5741.957129 5742.115129 5758.265035 5762.22541  5762.498535 5762.547316
 5790.083473 5794.770754 5795.066754 5824.328473 5828.352504 5828.724379
 5828.759941 5828.90591  5829.015004 5841.45

In [20]:
print(events["trial_start"])

[5045.206647 5052.14207  5060.594854 5068.269771 5077.096478 5088.73107
 5097.065748 5104.881732 5117.277762 5124.808765 5131.485896 5142.068073
 5152.583054 5160.14184  5167.832896 5174.729315 5184.058115 5194.087559
 5206.177729 5212.585876 5221.632926 5227.723325 5238.562843 5244.745061
 5253.141991 5260.786113 5267.23493  5274.603045 5282.766819 5294.631672
 5323.881499 5338.535039 5349.077723 5361.17817  5383.524297 5390.13206
 5400.823934 5412.696926 5423.861948 5434.093331 5445.22898  5453.355816
 5464.038991 5474.42599  5481.465003 5508.545393 5524.380298 5544.247831
 5561.588143 5576.054986 5586.154865 5597.998333 5607.458853 5625.246504
 5635.354405 5644.065849 5657.721882 5664.633435 5675.13004  5682.983819
 5700.5422   5707.160369 5715.862633 5725.478095 5735.356839 5746.064971
 5759.899474 5766.585427 5791.752142 5800.01902  5810.179446 5816.593046
 5825.987662 5834.252896 5843.145033 5852.428908 5866.928167 5873.964311
 5886.988245]


In [21]:
print(events["trial_end"])

[5042.997691 5050.558391 5059.20828  5066.65933  5075.474422 5087.197521
 5095.568276 5103.299447 5115.796819 5123.214521 5129.983699 5140.529056
 5151.242597 5158.80364  5166.504576 5173.382047 5182.545509 5192.728644
 5204.844162 5211.181584 5220.305069 5226.393375 5237.087161 5243.274911
 5251.675021 5259.326199 5265.685567 5273.115565 5281.295608 5293.154141
 5322.410363 5337.191219 5347.754595 5359.780617 5382.172205 5388.809546
 5399.464063 5411.241277 5422.525558 5432.748616 5443.873233 5451.934528
 5462.699705 5473.054868 5480.110988 5507.147957 5523.059848 5542.925471
 5560.249055 5574.647655 5584.842005 5596.687049 5606.130491 5623.924464
 5634.016183 5642.749218 5656.406356 5663.245752 5673.799266 5681.672117
 5699.224456 5705.762575 5714.553553 5724.157604 5734.030377 5744.674287
 5758.573194 5765.264112 5790.38777  5798.570065 5808.840511 5815.249657
 5824.642278 5832.912146 5841.785746 5851.079746 5865.598701 5872.617754
 5885.424117 5893.326735]


In [6]:
print(len(events["trial_start"]), len(events["trial_end"]))

79 80


In [7]:
events["trial_start"]

array([5045.206647, 5052.14207 , 5060.594854, 5068.269771, 5077.096478,
       5088.73107 , 5097.065748, 5104.881732, 5117.277762, 5124.808765,
       5131.485896, 5142.068073, 5152.583054, 5160.14184 , 5167.832896,
       5174.729315, 5184.058115, 5194.087559, 5206.177729, 5212.585876,
       5221.632926, 5227.723325, 5238.562843, 5244.745061, 5253.141991,
       5260.786113, 5267.23493 , 5274.603045, 5282.766819, 5294.631672,
       5323.881499, 5338.535039, 5349.077723, 5361.17817 , 5383.524297,
       5390.13206 , 5400.823934, 5412.696926, 5423.861948, 5434.093331,
       5445.22898 , 5453.355816, 5464.038991, 5474.42599 , 5481.465003,
       5508.545393, 5524.380298, 5544.247831, 5561.588143, 5576.054986,
       5586.154865, 5597.998333, 5607.458853, 5625.246504, 5635.354405,
       5644.065849, 5657.721882, 5664.633435, 5675.13004 , 5682.983819,
       5700.5422  , 5707.160369, 5715.862633, 5725.478095, 5735.356839,
       5746.064971, 5759.899474, 5766.585427, 5791.752142, 5800.

In [8]:
events["trial_end"]

array([5042.997691, 5050.558391, 5059.20828 , 5066.65933 , 5075.474422,
       5087.197521, 5095.568276, 5103.299447, 5115.796819, 5123.214521,
       5129.983699, 5140.529056, 5151.242597, 5158.80364 , 5166.504576,
       5173.382047, 5182.545509, 5192.728644, 5204.844162, 5211.181584,
       5220.305069, 5226.393375, 5237.087161, 5243.274911, 5251.675021,
       5259.326199, 5265.685567, 5273.115565, 5281.295608, 5293.154141,
       5322.410363, 5337.191219, 5347.754595, 5359.780617, 5382.172205,
       5388.809546, 5399.464063, 5411.241277, 5422.525558, 5432.748616,
       5443.873233, 5451.934528, 5462.699705, 5473.054868, 5480.110988,
       5507.147957, 5523.059848, 5542.925471, 5560.249055, 5574.647655,
       5584.842005, 5596.687049, 5606.130491, 5623.924464, 5634.016183,
       5642.749218, 5656.406356, 5663.245752, 5673.799266, 5681.672117,
       5699.224456, 5705.762575, 5714.553553, 5724.157604, 5734.030377,
       5744.674287, 5758.573194, 5765.264112, 5790.38777 , 5798.

In [12]:
stops = events["trial_start"]
starts = events["trial_end"][:-1]
trials = nept.Epoch(starts, stops)

In [9]:
starts = events["trial_start"]
stops = events["trial_end"]
trials = nept.Epoch(starts, stops)

ValueError: must have the same number of start and stop times

In [14]:
trials.durations

array([2.208956, 1.583679, 1.386574, 1.610441, 1.622056, 1.533549,
       1.497472, 1.582285, 1.480943, 1.594244, 1.502197, 1.539017,
       1.340457, 1.3382  , 1.32832 , 1.347268, 1.512606, 1.358915,
       1.333567, 1.404292, 1.327857, 1.32995 , 1.475682, 1.47015 ,
       1.46697 , 1.459914, 1.549363, 1.48748 , 1.471211, 1.477531,
       1.471136, 1.34382 , 1.323128, 1.397553, 1.352092, 1.322514,
       1.359871, 1.455649, 1.33639 , 1.344715, 1.355747, 1.421288,
       1.339286, 1.371122, 1.354015, 1.397436, 1.32045 , 1.32236 ,
       1.339088, 1.407331, 1.31286 , 1.311284, 1.328362, 1.32204 ,
       1.338222, 1.316631, 1.315526, 1.387683, 1.330774, 1.311702,
       1.317744, 1.397794, 1.30908 , 1.320491, 1.326462, 1.390684,
       1.32628 , 1.321315, 1.364372, 1.448955, 1.338935, 1.343389,
       1.345384, 1.34075 , 1.359287, 1.349162, 1.329466, 1.346557,
       1.564128])

In [ ]:
if len(events["trial_start"]) > len(events["trial_end"]):
    print("ere")
    starts = events["trial_start"][:-1]
    stops = events["trial_end"]
elif len(events["trial_start"]) < len(events["trial_end"]):
    print("bdhj")
    starts = events["trial_start"]
    stops = events["trial_end"][:-1]
else:
    print("ujk")
    starts = events["trial_start"]
    stops = events["trial_end"]
trials = nept.Epoch(starts, stops)

In [ ]:
trials.n_epochs

In [ ]:
print("Mean duration: ", np.round(np.mean(trials.durations), 1), "seconds")

In [ ]:
feeders = ["north_feeder", "east_feeder", "south_feeder"]
photobeams = ["north_pb", "east_pb", "south_pb"]

In [ ]:
fig, ax = plt.subplots()
legend = []
for feeder in feeders:
    plt.plot(events[feeder], np.ones(len(events[feeder])), "|", ms=10, mew=5)
    legend.append(feeder)
    
for photobeam in photobeams:
    plt.plot(events[photobeam], np.ones(len(events[photobeam]))+0.1, "|", ms=10, mew=1)
#     legend.append(photobeam)
    
ax.axes.get_yaxis().set_visible(False)
ax.spines['top'].set_visible(False)
plt.xlabel("time (s)")
plt.legend(legend)
plt.title("Test T-maze")
plt.ylim(0, 2)

plt.show()